# Generated by Django 5.2.1 on 2025-06-01 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.target')),
            ],
        ),
        migrations.CreateModel(
            name='DomainCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('days_to_expiry', models.IntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain_check', to='api.target')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('latency_ms', models.FloatField()),
                ('checked_at', models.DateTimeField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='api.target')),
            ],
        ),
        migrations.CreateModel(
            name='SSLCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('days_to_expiry', models.IntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_check', to='api.target')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('latency_ms', models.FloatField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='api.target')),
            ],
        ),
    ]
