# Generated by Django 5.2.1 on 2025-06-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_target_url_alert_domaincheck_history_sslcheck_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='target',
            new_name='target_url',
        ),
        migrations.RenameField(
            model_name='domaincheck',
            old_name='target',
            new_name='target_url',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='target',
            new_name='target_url',
        ),
        migrations.RenameField(
            model_name='sslcheck',
            old_name='target',
            new_name='target_url',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='target',
            new_name='target_url',
        ),
    ]
