# Generated by Django 5.2.1 on 2025-06-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_target_alert_target_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='status',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
