# Generated by Django 5.2.1 on 2025-06-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_statuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='response_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
