services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: group_db
      POSTGRES_USER: netumo
      POSTGRES_PASSWORD: netumo
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  backend:
    build: .
    command: gunicorn mini_netumo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A mini_netumo worker -l info
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      - backend
      - redis

  beat:
    build: .
    command: celery -A mini_netumo beat -l info
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      - backend
      - redis

  vue-frontend:
    build: .
    ports:
      - "3001:80"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - vue-frontend

volumes:
  pgdata:
